BATCH_SIZE = 512
MOMENTUM = 0.9
LEARNING_RATE = 0.4
WEIGHT_DECAY = 5e-4
EPOCHS = 24

CUTOUT_PIXELS = 8
RANDOM_CROP_DIMS = [32, 32, 3]

TF_RECORD_TRAIN_FILEPATH = '/content/train.tfrecords'
TF_RECORD_TEST_FILEPATH = '/content/test.tfrecords'
